### ISSUE TITLE
Remove algorithms and data structures

### ISSUE THREAD

**Issue by jelisejev** [ctco-dev/architect-requirements#9]
> Algorithms and Data Structures
Programming Paradigms (OOP, AOP, functional, imperative, declarative)

I believe these two points are too low-level and platform-specific to be relevant for an architect. It's the job of the developers of the projects to pick out particular algorithms and data structures that are suitable for their task.

**Comment by arbitertl** [comment]
Regarding algorithms. Architect should have understanding on the following topics:

- O(n) complexity (in fact scalability)
- Memory vs performance aspects
- Recursive vs iterative
- Greediness, memoization concepts

**Comment by arbitertl** [comment]
Regarding Paradigms. Architect should understand benefits and tradeofs of different paradigms and understand their terminology. This doesn't imply practical experience with all of them.

**Comment by ialexandrov** [comment]
Software Architect is growing from (good) Software Developers. Development supervision and final technical decision call are among architects' major responsibilities. So I would consider this skill as crucial for Software Architect. 
Also I don't see how this topic is platform specific. This is general theory.

BTW suggestion to add machine learning and blockchain topics (which are both algorithm related) together with removal of general algorithm topic looks a bit strange and inconsistent:)

**Comment by jelisejev** [comment]
The reason why I ask this question is because I try to understand, if the given skills are applicable to everyday work an architect has to do. And an architect's main task is designing whole systems, not implementing additional components. From that perspective, what @nikita-golovin mentions can be split into 3 groups:
1. High-level concepts (e.g. concurrency) - we should try to come up with a list of concepts, that can help you understand the fundamentals of any language. E.g. you won't be able to write JS without understanding what async execution is or write Go without understanding concurrency. But you are not expected to know the implementation details and low-level underlying structures, such as channels in Go. That brings us to point 2.
2. Data structures - these are really dependant on the platform you work with. I would expect a Java developer to know the difference between all of the types of maps Java has, however, many languages don't have such a concept explicitly (JS, Go, Python). They implement a hash map under the hood, but, again, these are low-level details.
3. Algorithms - these are very specific to a particular problem. Most of them are really relevant to dealing with large amounts of data which is not a usual use case for us. These are particular solutions for a particular problem, and like mentioned before, I wouldn't expect an arhitect to be able to solve any problem. Otherwise we might as well ask about how CSS works, because that's much more relevant for most of the projects that we do.

@ialexandrov I didn't suggest adding these, I merely noted them down. As a matter of fact, I'm against those.

**Comment by arbitertl** [comment]
1. Actually I meant concurrency in terms of data structure thread-safety and algorithm scalability (not how asynchronous calls are working in certain language runtime)
2. I'm talking about conceptual data structures and not their implementations in concrete frameworks (which are usually though more or less canonical). Ofc some languages can miss certain structures - that's totally fine.
3. Everything I mentioned reg. algorithm is not problem-specific (except for basic algorithm examples - "quick sort" is obviously for sorting problem :) )

**Comment by jelisejev** [comment]
1. Concurrent data structures are either language-specific, for runtimes, that actually support concurrency or parallelism, or problem specific (see my point in 3)
2. A hash map seems like a very concrete implementation to me. A conceptual structure would be just a map. Again, many runtimes don't have a notion of a hash map. Just a map.
3. Knowledge of these algorithms mostly becomes important when dealing with large amounts of data (backend) or aiming for optimal performance in certain cases (e.g. moving stuff around on the UI). You don't really care using which algorithms you sort 100 elements on modern hardware, don't you? This is what I mean by being "problem specific" It's not relevant for all of the use cases, but where it is, it should be discussed in the scope of a particular problem and specific technology.

**Comment by nikita-golovin** [comment]
Voting closed. Topic remains
